# ABOUTME: Datafile: reads the records of one CronosPro .dat file through its .tad index.
# ABOUTME: Handles v3/v4 headers, extension blocks, KOD decoding and zlib decompression.
import io
import struct
import sys
import zlib
from typing import NamedTuple

from . import koddecoder
from .hexdump import tohex, toout


class ExtendedRecord(NamedTuple):
    """
    A record reassembled from extension blocks.

    `tail` holds the bytes read past the record's end; `chain` holds the first block offset from the record
    header followed by the next-block offset read from each extension block.
    """

    data: bytes
    tail: bytes
    length: int
    chain: list[int]


class Datafile:
    """Represent a single .dat with it's .tad index file"""

    def __init__(self, name, dat, tad, compact, kod):
        self.name = name
        self.dat = dat
        self.tad = tad
        self.compact = compact

        self.readdathdr()
        self.readtad()

        self.dat.seek(0, io.SEEK_END)
        self.datsize = self.dat.tell()

        self.kod = kod if not kod or self.isencrypted() else koddecoder.new()

    def close(self):
        """
        Close the .dat and .tad files.
        """
        self.dat.close()
        self.tad.close()

    def isencrypted(self):
        return self.version in (b"01.04", b"01.05") or self.isv4()

    def isv3(self):
        #  01.02: 32 bit file offsets
        #  01.03: 64 bit file offsets
        #  01.04:  encrypted?, 32bit
        #  01.05:  encrypted?, 64bit
        return self.version in (b"01.02", b"01.03", b"01.04", b"01.05")

    def isv4(self):
        #  01.11  v4 ( 64bit )
        #  01.14  v4 ( 64bit ), encrypted?
        #  01.13  ?? I have not seen this version anywhere yet.
        return self.version in (b"01.11", b"01.13", b"01.14")

    def isv7(self):
        #  01.19  ?? I have not seen this version anywhere yet.
        return self.version in (b"01.19",)

    def readdathdr(self):
        """
        Read the .dat file header.
        Note that the 19 byte header if followed by 0xE9 random bytes, generated by
        'srand(time())' followed by 0xE9 times obfuscate(rand())
        """
        self.dat.seek(0)
        hdrdata = self.dat.read(19)

        (
            magic,  # +00  8 bytes
            self.hdrunk,  # +08  uint16
            self.version,  # +0a  5 bytes
            self.encoding,  # +0f  uint16
            self.blocksize,  # +11  uint16
        ) = struct.unpack("<8sH5sHH", hdrdata)

        if magic != b"CroFile\x00":
            raise ValueError(f"Cro{self.name}.dat is not a Cronos file: unknown magic {magic!r}")
        self.use64bit = self.version in (b"01.03", b"01.05", b"01.11")

        # blocksize
        #   0040 -> Bank
        #   0400 -> Index or Sys
        #   0200 -> Stru  or Sys

        # encoding
        #   bit0 = 'KOD encoded'
        #   bit1 = compressed

    def readtad(self):
        """
        read and decode the .tad file.
        """
        self.tad.seek(0)
        if self.isv3():
            hdrdata = self.tad.read(2 * 4)
            self.nrdeleted, self.firstdeleted = struct.unpack("<2L", hdrdata)
        elif self.isv4():
            hdrdata = self.tad.read(4 * 4)
            _unk1, self.nrdeleted, self.firstdeleted, _unk2 = struct.unpack("<4L", hdrdata)
        else:
            raise Exception("unsupported .tad version")

        self.tadhdrlen = self.tad.tell()
        self.tadentrysize = 16 if self.use64bit else 12
        if self.compact:
            self.tad.seek(0, io.SEEK_END)
        else:
            self.idxdata = self.tad.read()
        self.tadsize = self.tad.tell() - self.tadhdrlen
        self.nrofrecords = self.tadsize // self.tadentrysize
        if self.tadsize % self.tadentrysize:
            print("WARN: leftover data in .tad", file=sys.stderr)

    def tadidx(self, idx):
        """
        If we're not supposed to be more compact but slower, lookup from a cached .tad
        """
        if self.compact:
            return self.tadidx_seek(idx)

        if self.use64bit:
            # 01.03 and 01.11 have 64 bit file offsets
            return struct.unpack_from("<QLL", self.idxdata, idx * self.tadentrysize)
        else:
            # 01.02  and 01.04  have 32 bit offsets.
            return struct.unpack_from("<LLL", self.idxdata, idx * self.tadentrysize)

    def tadidx_seek(self, idx):
        """
        Memory saving version without caching the .tad
        """
        self.tad.seek(self.tadhdrlen + idx * self.tadentrysize)
        idxdata = self.tad.read(self.tadentrysize)

        if self.use64bit:
            # 01.03 and 01.11 have 64 bit file offsets
            return struct.unpack("<QLL", idxdata)
        else:
            # 01.02  and 01.04  have 32 bit offsets.
            return struct.unpack("<LLL", idxdata)

    def readdata(self, ofs, size):
        """
        Read raw data from the .dat file
        """
        self.dat.seek(ofs)
        return self.dat.read(size)

    def readrec(self, idx):
        """
        Extract and decode a single record.
        """
        if idx == 0:
            raise Exception("recnum must be a positive number")
        ofs, ln, _chk = self.tadidx(idx - 1)
        if ln == 0xFFFFFFFF:
            # deleted record
            return

        if self.isv3():
            flags = ln >> 24
            ln &= 0xFFFFFFF
        elif self.isv4():
            flags = ofs >> 56
            ofs &= (1 << 56) - 1
        else:
            raise ValueError(f"unsupported Cronos file version {self.version!r} in Cro{self.name}.dat")

        dat = self.readdata(ofs, ln)

        if not dat:
            # empty record
            encdat = dat
        elif not flags:
            encdat = self.readextendedrecord(idx, dat).data
        else:
            encdat = dat

        if self.encoding & 1 and self.kod:
            encdat = self.kod.decode(idx, encdat)

        if self.iscompressed(encdat):
            encdat = self.decompress(encdat)

        return encdat

    def readextendedrecord(self, idx, dat):
        """
        Reassemble record `idx` from extension blocks, given `dat`, the record's first block.

        The first block holds the offset of the first extension block, the record length, then data; each
        extension block starts with the offset of the next one. Raises ValueError when the header is truncated,
        the length exceeds the file, the blocks loop, or a block lies past the end of the file.
        """
        headersize, pointersize, pointerformat = (12, 8, "<Q") if self.use64bit else (8, 4, "<L")
        where = f"record {idx} in Cro{self.name}.dat"
        if len(dat) < headersize:
            raise ValueError(f"{where} is shorter than its {headersize}-byte extended record header")
        extofs, extlen = struct.unpack("<QL" if self.use64bit else "<LL", dat[:headersize])
        if extlen > self.datsize:
            raise ValueError(f"{where} claims {extlen} bytes, more than the file holds")

        encdat = dat[headersize:]
        chain = [extofs]
        while len(encdat) < extlen:
            if extofs in chain[:-1]:
                raise ValueError(f"{where} has a loop in its extension blocks at offset {extofs:#x}")
            block = self.readdata(extofs, self.blocksize)
            if len(block) <= pointersize:
                raise ValueError(f"{where} has an extension block past the end of the file at offset {extofs:#x}")
            (extofs,) = struct.unpack(pointerformat, block[:pointersize])
            chain.append(extofs)
            encdat += block[pointersize:]
        return ExtendedRecord(encdat[:extlen], encdat[extlen:], extlen, chain)

    def enumrecords(self):
        for i in range(self.nrofrecords):
            yield self.readrec(i + 1)

    def enumunreferenced(self, ranges, filesize):
        """
        From a list of used byte ranges and the filesize, enumerate the list of unused byte ranges
        """
        o = 0
        for start, end, _desc in sorted(ranges):
            if start > o:
                yield o, start - o
            o = end
        if o < filesize:
            yield o, filesize - o

    def dump(self, args):
        """
        Dump decodes all data referenced from the .tad file.
        And optionally print out all unreferenced byte ranges in the .dat file.

        This function is mostly useful for reverse-engineering the database format.

        the `args` object controls how data is decoded.
        """
        print(
            f"hdr: {self.name:<6} dat: {self.hdrunk:04x} {self.version} "
            f"enc:{self.encoding:04x} bs:{self.blocksize:04x}, "
            f"tad: {self.nrdeleted:08x} {self.firstdeleted:08x}"
        )

        ranges = []  # keep track of used bytes in the .dat file.

        for i in range(self.nrofrecords):
            (ofs, ln, chk) = self.tadidx(i)
            idx = i + 1
            if args.maxrecs and i == args.maxrecs:
                break
            if ln == 0xFFFFFFFF:
                print(f"{idx:5d}: {ofs:08x} {ln:08x} {chk:08x}")
                continue

            if self.isv3():
                flags = ln >> 24
                ln &= 0xFFFFFFF
            elif self.isv4():
                flags = ofs >> 56
                # 04 --> data, v3compdata
                # 02,03 --> deleted
                # 00 --> extrec
                ofs &= (1 << 56) - 1
            else:
                raise ValueError(f"unsupported Cronos file version {self.version!r} in Cro{self.name}.dat")

            dat = self.readdata(ofs, ln)
            ranges.append((ofs, ofs + ln, f"item #{i:d}"))
            decflags = [" ", " "]
            infostr = ""
            tail = b""

            if not dat:
                # empty record
                encdat = dat
            elif not flags:
                try:
                    extended = self.readextendedrecord(idx, dat)
                except ValueError as e:
                    print(f"{idx:5d}: {ofs:08x}-{ofs + ln:08x}: ({flags:02x}:{chk:08x}) <{e}>")
                    continue
                infostr = ";".join(
                    f"{value:08x}" for value in [extended.chain[0], extended.length, *extended.chain[1:]]
                )
                for blockofs in extended.chain[:-1]:
                    ranges.append((blockofs, blockofs + self.blocksize, f"item #{i:d} ext"))
                encdat, tail = extended.data, extended.tail
                decflags[0] = "+"
            else:
                encdat = dat
                decflags[0] = "*"

            if self.encoding & 1:
                if self.kod:
                    encdat = self.kod.decode(idx, encdat)
            else:
                decflags[0] = " "

            if args.decompress and self.iscompressed(encdat):
                encdat = self.decompress(encdat)
                decflags[1] = "@"

            # TODO: separate handling for v4
            print(
                f"{i + 1:5d}: {ofs:08x}-{ofs + ln:08x}: ({flags:02x}:{chk:08x}) "
                f"{infostr} {''.join(decflags)}{toout(args, encdat)} {tohex(tail)}"
            )

        if args.verbose:
            # output parts not referenced in the .tad file.
            for o, length in self.enumunreferenced(ranges, self.datsize):
                dat = self.readdata(o, length)
                print(f"{o:08x}-{o + length:08x}: {toout(args, dat)}")

    def iscompressed(self, data):
        """
        Check if this record looks like a compressed record.
        """
        if len(data) < 11:
            return
        if data[-3:] != b"\x00\x00\x02":
            return
        o = 0
        while o < len(data) - 3:
            size, flag = struct.unpack_from(">HH", data, o)
            if flag != 0x800 and flag != 0x008:
                return
            o += size + 2
        return True

    def decompress(self, data):
        """
        Decompress a record.

        Compressed records can have several chunks of compressed data.
        Note that the compression header uses a mix of big-endian and little numbers.

        each chunk has the following format:
            size  - big endian uint16, size of flag + crc + compdata
            flag  - big endian uint16 - always 0x800
            crc   - little endian uint32, crc32 of the decompressed data
        the final chunk has only 3 bytes: a zero size followed by a 2.

        the crc algorithm is the one labeled 'crc-32' on this page:
            http://crcmod.sourceforge.net/crcmod.predefined.html
        """
        result = b""
        o = 0
        while o < len(data) - 3:
            # note the mix of bigendian and little endian numbers here.
            size, _flag = struct.unpack_from(">HH", data, o)
            (_storedcrc,) = struct.unpack_from("<L", data, o + 4)

            C = zlib.decompressobj(-15)
            result += C.decompress(data[o + 8 : o + 8 + size - 6])
            # note that we are not verifying the crc!

            o += size + 2
        return result
