# ABOUTME: Datafile: reads the records of one CronosPro .dat file through its .tad index.
# ABOUTME: Decodes each record through _format/record.py and dumps them, byte range by byte range, for inspect.
import argparse
import io
from collections.abc import Callable, Iterator
from typing import BinaryIO

from . import koddecoder
from ._format.header import read_dat_header
from ._format.record import RecordParts, RecordSource, decode_record, decompress, is_compressed, read_stored
from ._format.tad import TadEntry, tad_layout
from .hexdump import tohex, toout, warn_on_stderr
from .koddecoder import KODcoding


class Datafile:
    """Represent a single .dat with it's .tad index file"""

    def __init__(
        self,
        name: str,
        dat: BinaryIO,
        tad: BinaryIO,
        compact: bool,
        kod: KODcoding | None,
        warn: Callable[[str], None] = warn_on_stderr,
    ) -> None:
        self.warn = warn
        self.name = name
        self.dat = dat
        self.tad = tad
        self.compact = compact

        self.readdathdr()
        self.readtad()

        self.dat.seek(0, io.SEEK_END)
        self.datsize = self.dat.tell()

        # A file that is not encrypted with its own KOD table is decoded with the default one, whatever KOD is given.
        self.kod = kod if kod is None or self.header.own_kod else koddecoder.new()
        self.source = RecordSource(
            self.name,
            self.readdata,
            self.datsize,
            self.blocksize,
            self.use64bit,
            self.kod if self.encoding & 1 else None,
        )

    def close(self) -> None:
        """
        Close the .dat and .tad files.
        """
        self.dat.close()
        self.tad.close()

    def readdathdr(self) -> None:
        """
        Read the .dat file header.
        Note that the 19 byte header if followed by 0xE9 random bytes, generated by
        'srand(time())' followed by 0xE9 times obfuscate(rand())
        """
        header = read_dat_header(self.dat, where=f"Cro{self.name}.dat")
        layout = tad_layout(header.version)
        if layout is None:
            raise ValueError(
                f"Cro{self.name}.dat is CronosPro version {header.version_text}, whose .tad index this release "
                "cannot read"
            )
        self.header = header
        self.layout = layout
        self.hdrunk = header.unknown
        self.version = header.version
        self.encoding = header.encoding
        self.blocksize = header.blocksize
        self.use64bit = header.use64bit

        # blocksize
        #   0040 -> Bank
        #   0400 -> Index or Sys
        #   0200 -> Stru  or Sys

        # encoding
        #   bit0 = 'KOD encoded'
        #   bit1 = compressed

    def readtad(self) -> None:
        """
        read and decode the .tad file.
        """
        self.tad.seek(0)
        header_size = self.layout.header.size
        hdrdata = self.tad.read(header_size)
        if len(hdrdata) < header_size:
            raise ValueError(f"Cro{self.name}.tad is shorter than its {header_size}-byte header")
        self.nrdeleted, self.firstdeleted = self.layout.deleted_counts(hdrdata)

        self.tadhdrlen = self.tad.tell()
        self.tadentrysize = self.layout.entry.size
        self.idxdata = b""
        if self.compact:
            self.tad.seek(0, io.SEEK_END)
        else:
            self.idxdata = self.tad.read()
        self.tadsize = self.tad.tell() - self.tadhdrlen
        self.nrofrecords = self.tadsize // self.tadentrysize
        if self.tadsize % self.tadentrysize:
            self.warn("WARN: leftover data in .tad")

    def entry(self, index: int) -> TadEntry:
        """
        The .tad entry of the record at `index`, counted from 0. With `compact`, it is read from the .tad file
        instead of the cached copy.

        Raises ValueError naming the file and the index when it is not 0 to nrofrecords - 1.
        """
        if not 0 <= index < self.nrofrecords:
            raise ValueError(
                f"Cro{self.name}.tad has no entry {index}; its entries are numbered 0 to {self.nrofrecords - 1}"
            )
        if self.compact:
            self.tad.seek(self.tadhdrlen + index * self.tadentrysize)
            raw = self.tad.read(self.tadentrysize)
        else:
            start = index * self.tadentrysize
            raw = self.idxdata[start : start + self.tadentrysize]
        return self.layout.parse(raw)

    def readdata(self, ofs: int, size: int) -> bytes:
        """
        Read raw data from the .dat file
        """
        self.dat.seek(ofs)
        return self.dat.read(size)

    def read_record(self, recno: int) -> RecordParts | None:
        """
        Record `recno`, counted from 1, decoded and decompressed, or None when it is deleted.
        Raises ValueError, naming the record and the file, when it is not in the file or cannot be decoded.
        """
        if not 1 <= recno <= self.nrofrecords:
            raise ValueError(
                f"Cro{self.name}.dat has no record {recno}; its records are numbered 1 to {self.nrofrecords}"
            )
        entry = self.entry(recno - 1)
        if entry.deleted:
            return None
        return decode_record(self.source, recno, entry)

    def readrec(self, recno: int) -> bytes | None:
        """
        Extract and decode a single record, or None when it is deleted.
        Compressed data whose CRC-32 does not match is kept and reported through `warn`.
        Raises ValueError when the record is not in the file or cannot be decoded.
        """
        parts = self.read_record(recno)
        if parts is None:
            return None
        if parts.mismatched_chunks:
            self.warn(
                f"WARN: record {recno} in Cro{self.name}.dat has compressed data whose checksum does not match; "
                "it is kept"
            )
        return parts.data

    def enumunreferenced(self, ranges: list[tuple[int, int, str]], filesize: int) -> Iterator[tuple[int, int]]:
        """
        From a list of used byte ranges and the filesize, enumerate the list of unused byte ranges
        """
        o = 0
        for start, end, _desc in sorted(ranges):
            if start > o:
                yield o, start - o
            o = end
        if o < filesize:
            yield o, filesize - o

    def dump(self, args: argparse.Namespace) -> None:
        """
        Dump decodes all data referenced from the .tad file.
        And optionally print out all unreferenced byte ranges in the .dat file.

        This function is mostly useful for reverse-engineering the database format.

        the `args` object controls how data is decoded.
        """
        print(
            f"hdr: {self.name:<6} dat: {self.hdrunk:04x} {self.version} "
            f"enc:{self.encoding:04x} bs:{self.blocksize:04x}, "
            f"tad: {self.nrdeleted:08x} {self.firstdeleted:08x}"
        )

        ranges: list[tuple[int, int, str]] = []  # keep track of used bytes in the .dat file.

        for i in range(self.nrofrecords):
            entry = self.entry(i)
            idx = i + 1
            if args.maxrecs and i == args.maxrecs:
                break
            if entry.deleted:
                print(f"{idx:5d}: {entry.offset:08x} {entry.length:08x} {entry.checksum:08x}")
                continue

            ofs, ln, flags, chk = entry.offset, entry.length, entry.flags, entry.checksum
            ranges.append((ofs, ofs + ln, f"item #{i:d}"))
            decflags = [" ", " "]
            infostr = ""

            try:
                parts = read_stored(self.source, idx, entry, require_whole=False)
            except ValueError as e:
                print(f"{idx:5d}: {ofs:08x}-{ofs + ln:08x}: ({flags:02x}:{chk:08x}) <{e}>")
                continue
            if parts.extended:
                infostr = ";".join(f"{value:08x}" for value in [parts.chain[0], parts.length, *parts.chain[1:]])
                for blockofs in parts.chain[:-1]:
                    ranges.append((blockofs, blockofs + self.blocksize, f"item #{i:d} ext"))
                decflags[0] = "+"
            elif parts.data:
                decflags[0] = "*"

            if not self.encoding & 1:
                decflags[0] = " "

            data = parts.data
            if args.decompress and is_compressed(data):
                try:
                    data, _ = decompress(data, f"record {idx} in Cro{self.name}.dat")
                except ValueError as e:
                    print(f"{idx:5d}: {ofs:08x}-{ofs + ln:08x}: ({flags:02x}:{chk:08x}) <{e}>")
                    continue
                decflags[1] = "@"

            # TODO: separate handling for v4
            print(
                f"{i + 1:5d}: {ofs:08x}-{ofs + ln:08x}: ({flags:02x}:{chk:08x}) "
                f"{infostr} {''.join(decflags)}{toout(args, data)} {tohex(parts.tail)}"
            )

        if args.verbose:
            # output parts not referenced in the .tad file.
            for o, length in self.enumunreferenced(ranges, self.datsize):
                dat = self.readdata(o, length)
                print(f"{o:08x}-{o + length:08x}: {toout(args, dat)}")
